import "@/styles/globals.css";
import "@uploadthing/react/styles.css";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "@/app/_components/TopNav";
import { Toaster } from "sonner";
import { PostHogProvider } from "@/components/PostHogProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <>
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
      <ClerkProvider>
        <PostHogProvider>
          <html lang="en" className={`${geist.variable}`}>
            <body className={`font-sans ${geist.variable} dark`}>
                <div className="grid h-screen grid-rows-[auto,1fr]">
                  <TopNav />
                  <main className={"overflow-y-scroll"}>{children}</main>
                </div>
                {modal}
                <div id="modal-root"></div>
            </body>
          </html>
        </PostHogProvider>
      </ClerkProvider>
      <Toaster />
    </>
  );
}
