import "@/styles/globals.css";
import "@uploadthing/react/styles.css";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import TopNav from "@/app/_components/TopNav";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable}`}>
      <NextSSRPlugin
        routerConfig={extractRouterConfig(ourFileRouter)}
      />
        <body className="flex flex-col gap-4">
        <div className="w-full">
          <TopNav/>
        </div>
        {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
